### ISSUE TITLE
Expect don't validate Dictionary arguments

### ISSUE THREAD

**Issue by Dracks** [mflint/SwiftMock#1]
The Expected function (MockExpectation > match) don't check arguments of type dictionary.

**Comment by mflint** [comment]
Thank-you @Dracks, it's on my list of things to do.

Pull requests welcome! :-p

I'm considering changing the `accept` fund in `MockCallHandler` protocol from:
`func accept(expectationReturnValue: Any?, functionName: String, args: Any?...) -> Any?`
to
`func accept(expectationReturnValue: Any?, functionName: String, args: Dictionary<String, Any?>) -> Any?`

so that a test can easily capture arguments by name:

```
var capturedArgument: String
mock.expect().call(
    mock.function3(mock.anyString()))
    .andCapture({ (args) -> Void in
        capturedArgument = args["towel"] as! String
    })
```

**Comment by Dracks** [comment]
Also, you've got a problem when the parameters are custom values. You should document that, (in the sample) because it can be a problem for anyone. 

Thanks for the library.

**Comment by mflint** [comment]
Yes, custom parameters are high in the TODO list.

I'll probably support that with a matcher protocol, which can be implemented in your test suite. 

I will look into it this evening :)

**Comment by mflint** [comment]
@Dracks I've updated the project to add support for matching custom types. Look for `MockMatcherExtension` example in the README.
