### ISSUE TITLE
It does not support @objc objects

### ISSUE THREAD

**Issue by RohitNegi** [mflint/SwiftMock#11]
The class which inherit from NSObject gets failed because objects are not equal.
For example 
class CustomModel: NSObject {}
class MyViewModel {
func validateBiometric() {
repo.validateCustomerBiometric(requestModel: CustomModel(),  success: {}, failure: {} )
}
}
//TestFile
mockRepo.expect { o in
            o.validateCustomerBiometric(requestModel: CustomModel()) { (_) in } failure: { (_) in }
        }.doing { (actionArgs) in
            self.capturedCompletionBlock = actionArgs[0] as? (() -> Void)
        }.returning(())

viewModel.validateBiometric()

//
verify()

**Comment by mflint** [comment]
Thank-you for filing this issue @RohitNegi.

Can you explain, please exactly how this is failing, and which objects are not equal?

Please also share your `MockRepo.validatgeCustomerBiometric(…)` function. Are you supplying an extra `CustomModel` argument to the `accept()` function?

**Comment by RohitNegi** [comment]
When we are creating object that inherit from NSObject it contains the address of the object. so when we create instance of that class every time new address is assigned to that instance. When this method func claimExpectation(_ callSummary: String) -> MockExpectation? get called it fails at expectation.callSummary == callSummary because both objects has different address.
for example
validateCustomerBiometric(requestModel:success:failure:) [Optional(<iPhoneDemo.ProfileInputModel: 0x600000e98290>),]
validateCustomerBiometric(requestModel:success:failure:) [Optional(<iPhoneDemo.ProfileInputModel: 0x600000ebd260>),]

 If CustomModel class does not inherit from NSObject then it creates the callSummary string like this for same type of objects.
validateCustomerBiometric(requestModel:success:failure:) [Optional(<iPhoneDemo.ProfileInputModel:),]

**Comment by mflint** [comment]
@RohitNegi, please also share your `MockRepo.validatgeCustomerBiometric(…)` function. Are you supplying an extra `CustomModel` argument to the `accept()` function?

**Comment by RohitNegi** [comment]
Complete Custom model is like below 
class CustomModel: NSObject {
    var details: [String: Any?]?
}
Mock method mentioned below.
func validateCustomerBiometric(requestModel: CustomModel, success: @escaping (ESavingResultModel) -> Void, failure: @escaping (Exception?) -> Void) {
        accept(checkArgs: [requestModel], actionArgs: [success, failure])
    }

But after changing above method to below one. I can compare the dict and if all the keys and values are same then verify() gives success and It comes inside doing block.
func validateCustomerBiometric(requestModel: CustomModel, success: @escaping (ESavingResultModel) -> Void, failure: @escaping (Exception?) -> Void) {
        accept(checkArgs: [requestModel. details], actionArgs: [success, failure])
    }

**Comment by mflint** [comment]
OK, I see what's wrong here.

When you supply a value to `checkArgs:`, the Mock calls `String(describing: argument)` in an _attempt_ to make a unique value for this expectation.

The expectation is for `<iPhoneDemo.ProfileInputModel: 0x600000e98290>`, but the actual value received is `<iPhoneDemo.ProfileInputModel: 0x600000ebd260>`. 

Even for non-@objc classes, this probably isn't good enough for your tests, because the expectation will only succeed if it receives the _same_ instance of `ProfileInputModel`.

I'd recommend you identify the properties in your model which _really matter_ to your test, and pass the values of those properties to the `accept()` function.

# Example

If you have this `Bus` model and a `Driver` protocol:

```
@objc
class Bus: NSObject {
    let licensePlate: String
    let color: String
    var fuelLevel: Float
    
    init(licensePlate: String, color: String) {
        self.licensePlate = licensePlate
        self.color = color
        self.fuelLevel = 1.0
    }
}

protocol Driver {
  func drive(bus: Bus)
}
```

If you make your mock like this:

```
func drive(bus: Bus) {
  accept(args: [bus])
}
```

then the mock will expect a specific instance of the object (`<__lldb_expr_30.Bus: 0x600000c2d650>`), and will never receive the same instance when the test executes.

Instead, I'd recommend changing your mock to pull out the important properties, to make sure the driver is driving the correct bus:

```
func drive(bus: Bus) {
  accept(args: [bus.licensePlate])
}
```

**Comment by mflint** [comment]
Incidentally, for anybody else reading:

If your model were a Swift struct:

```
struct Bus {
    let licensePlate: String
    let color: String
    var fuelLevel: Float
}
```

... and you called `accept()` with the `bus` value (not just `bus.licensePlate`), then the expected call would be `__lldb_expr_32.Bus(licensePlate: "12345", color: "red", fuelLevel: 1.0)`.

This looks useful, but in reality it still probably isn't what you want. A driver is assigned to a bus, no matter what colour the bus is today, or how full the fuel-tank is.

So it's always a good idea to pass carefully-selected properties into the `accept()` function: `bus.licensePlate` rather than the whole `bus` value.

**Comment by RohitNegi** [comment]
Thanks for your reply, Yes I am doing the same now, using the required only properties in accept function.
